# Generated by Django 5.1.4 on 2025-01-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='province',
            new_name='provience',
        ),
    ]
